{
	"version": 1599377176,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/background-sheet0.png",
		"images/bricks-sheet0.png",
		"images/bricks-sheet1.png",
		"images/bricks-sheet2.png",
		"images/ball-sheet0.png",
		"images/ball-sheet1.png",
		"images/plataform-sheet0.png",
		"images/ball_destroyer-sheet0.png",
		"images/overlay_background-sheet0.png",
		"images/restart_button-sheet0.png",
		"images/select_stage_button2-sheet0.png",
		"images/next_stage_button-sheet0.png",
		"images/trail_effect-sheet0.png",
		"images/ball_particle_destroyed.png",
		"images/select_stage_button1-sheet0.png",
		"images/neon_support-sheet0.png",
		"images/glass_particle.png",
		"images/background3-sheet0.png",
		"images/explosion_particle.png",
		"images/play_button-sheet0.png",
		"images/select_stage_icon-sheet0.png",
		"images/current_stage_indicator.png",
		"images/power_up-sheet0.png",
		"images/gameover_and_gamewin-sheet0.png",
		"images/game_title-sheet0.png",
		"images/background2-sheet0.png",
		"images/stage_numbers.png",
		"images/game_version_text-sheet0.png",
		"images/audio_button-sheet0.png",
		"images/audio_button-sheet1.png",
		"images/audio_button-sheet2.png",
		"images/select_stage_text-sheet0.png",
		"images/current_page_indicator-sheet0.png",
		"images/back_page_button-sheet0.png",
		"images/next_page_button-sheet0.png",
		"images/return_button-sheet0.png",
		"images/screen_position-sheet0.png",
		"images/loading_bar_background-sheet0.png",
		"images/loadin_text-sheet0.png",
		"images/loading_bar.png",
		"images/help_text-sheet0.png",
		"images/help_object-sheet0.png",
		"images/indicator_effect-sheet0.png",
		"images/indicator_effect-sheet1.png",
		"images/colision_bars-sheet0.png",
		"images/sprite-sheet0.png",
		"media/ball collision.ogg",
		"media/game over.ogg",
		"media/platform collision.ogg",
		"media/game win.ogg",
		"media/broken glass 2.ogg",
		"media/broken glass 1.ogg",
		"media/lamp.ogg",
		"media/button sound.ogg",
		"media/main music.ogg",
		"media/power up.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}